# -*- coding: utf-8 -*-
"""TR_AI_H_672021098_672021217

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkrjvoN4HLhfN14y_lv2G71BsqfRsF60
"""

!pip install easyocr

import easyocr
import cv2
from matplotlib import pyplot as plt
import numpy as np

IMAGE_PATH = '/content/halo.jpg' #Penginputan gambar manual melalui google colab

reader = easyocr.Reader(['en'])
result = reader.readtext(IMAGE_PATH)
result

for i in range(len(result)):
  print(result[i][1])

img = cv2.imread(IMAGE_PATH)
plt.imshow(img)
plt.show()

result[0][0]

img = cv2.imread(IMAGE_PATH)

for i in range(len(result)):
  top_left = tuple(result[i][0][0])
  bottom_right = tuple(result[i][0][2])
  img = cv2.rectangle(img,top_left,bottom_right,(255,0,255),3)

plt.imshow(img)
plt.show()